version: '3.9'

services:
  nginx:
    image: docker.io/library/nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: "host"
    restart: always

  rosblox-studio:
    image: ghcr.io/rosblox/studio:latest
    volumes:
      - ./studio/layout.json:/src/layout.json
    ports:
      - 8080:8080
    restart: always

  ros-rosbridge-suite:
    image: ghcr.io/rosblox/ros-rosbridge-suite:humble
    ports:
      - 9090:9090
    restart: always
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml

  ros-zed-ros2-wrapper:
    image: ghcr.io/rosblox/ros-zed-ros2-wrapper:foxy
    restart: always
    network_mode: "host"
    privileged: true
    volumes:
      - ./ros-zed-ros2-wrapper/settings:/usr/local/zed/settings
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command: ros2 launch zed_wrapper zedm.launch.py
